Repository softeerbootcamp4th/Team3-Caecae-BE, pull requests merged in 2024-08, with the labels that each got.

#13 test : 테스트코드 작성 연습을 위한 health check api 테스트 및 S3 통합테스트 코드 작성 (CC-111)
  .github/pull_request_template.md
  src/main/java/ai/softeer/caecae/admin/api/S3Controller.java
  src/main/java/ai/softeer/caecae/global/controller/HealthTestController.java
  src/main/java/ai/softeer/caecae/global/utils/S3Service.java
  src/test/java/ai/softeer/caecae/CaecaeApplicationTests.java
  src/test/java/ai/softeer/caecae/global/controller/HealthTestControllerTest.java
  src/test/java/ai/softeer/caecae/global/utils/S3ServiceTest.java
  src/test/resources/hyundai.png
Labels: 진우, feat📌

#18 feat : 레이싱게임 결과 등록 또는 업데이트 api 개발 (CC-120)
  src/main/java/ai/softeer/caecae/racinggame/api/RacingGameApi.java
  src/main/java/ai/softeer/caecae/racinggame/api/RacingGameController.java
  src/main/java/ai/softeer/caecae/racinggame/domain/dto/request/RegisterRacingGameResultRequestDto.java
  src/main/java/ai/softeer/caecae/racinggame/domain/dto/response/RegisterRacingGameResultResponseDto.java
  src/main/java/ai/softeer/caecae/racinggame/domain/entity/RacingGameParticipant.java
  src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameParticipantRepository.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameParticipantService.java
  src/main/java/ai/softeer/caecae/user/domain/dto/request/FindAndRegisterUserRequestDto.java
  src/main/java/ai/softeer/caecae/user/domain/dto/response/FindAndRegisterUserResponseDto.java
  src/main/java/ai/softeer/caecae/user/domain/entity/User.java
  src/main/java/ai/softeer/caecae/user/repository/UserRepository.java
  src/main/resources/data.sql
Labels: 진우, feat📌

#22 feat : 관리자가 숨은캐스퍼찾기 게임 기간을 등록(업데이트) 하는 api 생성 (CC-128)
  src/main/java/ai/softeer/caecae/admin/api/AdminController.java
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGame.java
  src/main/java/ai/softeer/caecae/findinggame/domain/enums/AnswerType.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindGameDbRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/java/ai/softeer/caecae/racinggame/domain/dto/request/RegisterFindingGamePeriodRequestDto.java
  src/main/java/ai/softeer/caecae/racinggame/domain/dto/response/RegisterFindingGamePeriodResponseDto.java
Labels: 진우, feat📌

#25 feat : 숨은그림찾기 게임 정답 정보를 업데이트하는 api 생성 (CC-129)
  src/main/java/ai/softeer/caecae/admin/api/AdminController.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/FindingGameAnswerDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/request/FindingGameDailyAnswerRequestDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/response/FindingGameDailyAnswerResponseDto.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminException.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminExceptionHandler.java
  src/main/java/ai/softeer/caecae/admin/service/AdminService.java
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGame.java
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGameAnswer.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameAnswerDbRepository.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameDbRepository.java
  src/main/java/ai/softeer/caecae/global/enums/ErrorCode.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameInfoService.java
Labels: 진우, feat📌

#26 refactor : Admin 도메인을 AdminFindingGame, AdminRacingGame 도메인으로 분리 (CC-132)
  src/main/java/ai/softeer/caecae/admin/api/AdminFindingGameController.java
  src/main/java/ai/softeer/caecae/admin/api/AdminRacingGameController.java
  src/main/java/ai/softeer/caecae/admin/api/S3Controller.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/request/S3RequestDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/response/RacingGameWinnerResponseDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/response/S3ResponseDto.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminFindingGameException.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminFindingGameExceptionHandler.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminRacingGameException.java
  src/main/java/ai/softeer/caecae/admin/domain/exception/AdminRacingGameExceptionHandler.java
  src/main/java/ai/softeer/caecae/admin/service/AdminFindingGameService.java
  src/main/java/ai/softeer/caecae/admin/service/AdminRacingGameService.java
  src/main/java/ai/softeer/caecae/admin/service/S3Service.java
  src/main/java/ai/softeer/caecae/global/api/HealthTestController.java
  src/main/java/ai/softeer/caecae/global/enums/ErrorCode.java
  src/main/java/ai/softeer/caecae/global/utils/.gitkeep
  src/test/java/ai/softeer/caecae/admin/service/S3ServiceTest.java
  src/test/java/ai/softeer/caecae/global/controller/HealthTestControllerTest.java
  src/test/java/ai/softeer/caecae/global/utils/S3ServiceTest.java
Labels: 진우

#27 feat : 숨은캐스퍼찾기 전체 게임 정보를 조회하는 api 작성 (CC-138)
  src/main/java/ai/softeer/caecae/findinggame/api/FindingGameController.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/FindingGameDailyInfo.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/response/FindingGameInfoResponseDto.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindGameDbRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/java/ai/softeer/caecae/global/config/CorsConfig.java
  src/main/java/ai/softeer/caecae/racinggame/api/RacingGameController.java
Labels: 진우, feat📌

#29 fix : 어드민 이미지 업로드 dto에 누락된 questionImageUrl 추가 (CC-148)
  src/main/java/ai/softeer/caecae/admin/domain/dto/request/FindingGameDailyAnswerRequestDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/response/FindingGameDailyAnswerResponseDto.java
  src/main/java/ai/softeer/caecae/admin/service/AdminFindingGameService.java
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGame.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
Labels: fix🔨, 진우

#28 test : 사용자가 숨은그림찾기 게임 정보를 조회하는 로직 테스트코드 작성, Clock 객체 모킹하여 LocalDateTime.now()에 주입 (CC-147)
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/java/ai/softeer/caecae/global/config/TimeConfig.java
  src/test/java/ai/softeer/caecae/findinggame/service/FindingGameServiceTest.java
Labels: 진우, feat📌

#31 feat : 스프링캐시 사용 및 레디스 비밀번호 설정 (CC-152)
  build.gradle
  src/main/java/ai/softeer/caecae/CaecaeApplication.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/java/ai/softeer/caecae/global/config/CacheConfig.java
  src/main/java/ai/softeer/caecae/global/config/RedisConfig.java
  src/main/java/ai/softeer/caecae/global/enums/CacheType.java
  src/main/resources/application.yml
Labels: 진우, feat📌

#32 feat : 숨은캐스퍼찾기 게임 가능 여부와 관련 정보를 반환하는 api (CC-154)
  src/main/java/ai/softeer/caecae/findinggame/api/FindingGameController.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/response/StartGameResponseDto.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindGameDbRepository.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameDbRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/java/ai/softeer/caecae/global/enums/CacheType.java
  src/test/java/ai/softeer/caecae/findinggame/service/FindingGameServiceTest.java
Labels: 익준, feat📌

#36 feat : 레이싱게임 결과 백분위 조회 이분탐색 로직 수정. 캐싱 및 스케줄링을 통한 성능 개선 (CC-160)
  src/main/java/ai/softeer/caecae/CaecaeApplication.java
  src/main/java/ai/softeer/caecae/global/enums/CacheType.java
  src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameRepository.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameCacheService.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameService.java
  src/test/java/ai/softeer/caecae/global/controller/HealthTestControllerTest.java
Labels: 진우, feat📌

#35 fix : 레이싱게임을 현재 이용할 수 없을 때 갱신되는 버그 (CC-161)
  src/main/java/ai/softeer/caecae/global/enums/ErrorCode.java
  src/main/java/ai/softeer/caecae/racinggame/api/RacingGameController.java
  src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameInfoRepository.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameInfoService.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameParticipantService.java
  src/test/java/ai/softeer/caecae/racinggame/service/RacingGameInfoServiceTest.java
Labels: 익준, feat📌

#38 chore : 스프링부트 어플리케이션에서 프로메테우스를 통해 메트릭을 수집하도록 설정 (CC-165)
  build.gradle
  src/main/resources/application.yml
Labels: 진우, feat📌

#37 feat : redis의 winner 해시셋에 존재하는 데이터를 주기적으로 삭제 (CC-164)
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameRedisRepository.java
  src/main/java/ai/softeer/caecae/global/utils/.gitkeep
  src/main/java/ai/softeer/caecae/global/utils/SystemTimeConvertor.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameCacheService.java
  src/main/resources/application.yml
  src/test/java/ai/softeer/caecae/global/utils/SystemTimeConvertorTest.java
Labels: 진우, feat📌

#39 feat : 레이싱 게임 공유하기 단축 URL생성, 단축 URL으로 접속하면 원래 URL로 리다렉션 (CC-153)
  src/main/java/ai/softeer/caecae/global/enums/ErrorCode.java
  src/main/java/ai/softeer/caecae/global/utils/Encrypt.java
  src/main/java/ai/softeer/caecae/shorturl/api/ShortUrlController.java
  src/main/java/ai/softeer/caecae/shorturl/domain/entity/ShortUrlEntity.java
  src/main/java/ai/softeer/caecae/shorturl/domain/exception/UrlException.java
  src/main/java/ai/softeer/caecae/shorturl/domain/exception/UrlExceptionHandler.java
  src/main/java/ai/softeer/caecae/shorturl/domain/request/ShareUrlRequestDto.java
  src/main/java/ai/softeer/caecae/shorturl/domain/response/ShareUrlResponseDto.java
  src/main/java/ai/softeer/caecae/shorturl/repository/ShortUrlRepository.java
  src/main/java/ai/softeer/caecae/shorturl/service/ShortUrlService.java
Labels: 익준, feat📌

#41 feat : 사용자가 힌트를 요청하는 api 및 로직 개발 (CC-168)
  src/main/java/ai/softeer/caecae/findinggame/api/FindingGameController.java
  src/main/java/ai/softeer/caecae/findinggame/api/FindingGamePlayController.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/PositionDto.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/request/HintRequestDto.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/response/HintResponseDto.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGamePlayService.java
  src/main/java/ai/softeer/caecae/global/enums/ErrorCode.java
Labels: 진우, feat📌

#43 fix : 레이싱 게임 추첨 당첨자 수 가져오기 및 NullPointerError 수정 (CC-175)
  src/main/java/ai/softeer/caecae/admin/service/AdminRacingGameService.java
Labels: 익준, feat📌

#42 test : 숨캐찾 게임 힌트 조회하는 api 테스트코드 작성, 어드민-숨캐찾 서비스로직 테스트코드 작성 (CC-173)
  src/main/java/ai/softeer/caecae/admin/service/AdminRacingGameService.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/request/AnswerRequestDto.java
  src/main/java/ai/softeer/caecae/findinggame/domain/dto/request/HintRequestDto.java
  src/main/java/ai/softeer/caecae/racinggame/service/RacingGameInfoService.java
  src/test/java/ai/softeer/caecae/admin/service/AdminFindingGameServiceTest.java
  src/test/java/ai/softeer/caecae/admin/service/AdminRacingGameServiceTest.java
  src/test/java/ai/softeer/caecae/findinggame/service/FindingGamePlayServiceTest.java
Labels: 진우

#44 feat : 레디스 마스터-슬레이브 구조에서 읽기작업을 슬레이브에서 하도록 변경 (CC-177)
  src/main/java/ai/softeer/caecae/global/config/RedisConfig.java
  src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameInfoRepository.java
  src/main/resources/application.yml
Labels: 진우, feat📌

#45 feat : 선착순 등록 시 병목을 막기 위한 스케쥴러 구현 (CC-176)
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGameRealWinner.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameRedisRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGamePlayService.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameScheduleService.java
Labels: 익준, feat📌

#46 fix : 스케쥴링을 통해 처리된 건이 있으면 로그 기록 (CC-176)
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameScheduleService.java
Labels: 익준, feat📌

#48 feat : 단축 URL공유 텍스트 수정, 이미지를 환경변수로 관리 (CC-179)
  src/main/java/ai/softeer/caecae/shorturl/service/ShortUrlService.java
  src/main/resources/application.yml
Labels: 진우, feat📌

#47 fix : DB 병목 개선 - FindingGameWinner에 데이터 넣을 때 NativeQuery사용 (CC-176)
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameWinnerRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameScheduleService.java
Labels: 익준, feat📌

#49 fix : 로그시간 KST로 수정 및 로그 바인딩 설정 추가 (CC-180)
  src/main/java/ai/softeer/caecae/admin/api/AdminFindingGameController.java
  src/main/java/ai/softeer/caecae/admin/api/AdminRacingGameController.java
  src/main/java/ai/softeer/caecae/admin/service/AdminFindingGameService.java
  src/main/java/ai/softeer/caecae/admin/service/AdminRacingGameService.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGamePlayService.java
  src/main/java/ai/softeer/caecae/user/domain/dto/request/FindAndRegisterUserRequestDto.java
  src/main/java/ai/softeer/caecae/user/domain/dto/response/FindAndRegisterUserResponseDto.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: fix🔨, 진우

#51 fix : 레이싱게임 추첨시 기존 데이터베이스 내용 삭제 (CC-181)
  src/main/java/ai/softeer/caecae/admin/service/AdminRacingGameService.java
Labels: fix🔨, 익준

#50 fix : 로직 위치 변경 및 스케쥴링 시간 변경 (CC-176)
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGamePlayService.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameScheduleService.java
Labels: fix🔨, 익준, feat📌

#53 fix : 레디스 빈 등록 오타 수정 (CC-183)
  src/main/java/ai/softeer/caecae/racinggame/repository/RacingGameInfoRepository.java
Labels: 진우, feat📌

#54 feat : 숨캐찾 게임 참여자 카운트를 스케줄링을 통해 0으로 만드는 로직 (CC-184)
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameRedisRepository.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameScheduleService.java
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
Labels: 진우, feat📌

#55 fix : 숨은캐스퍼찾기 게임 마지막날 일 때 인덱스 에러 해결 (hotfix-1)
  src/main/java/ai/softeer/caecae/findinggame/service/FindingGameService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: fix🔨, 익준

#58 docs : 아키텍처, ERD, 그라운드룰 추가
  README.md
Labels: 진우

#59 hotfix : 숨은캐스퍼찾기 당첨자 조회 로직 수정
  src/main/java/ai/softeer/caecae/admin/api/AdminFindingGameController.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/FindingGameWinnerDto.java
  src/main/java/ai/softeer/caecae/admin/domain/dto/response/FindingGameWinnerResponseDto.java
  src/main/java/ai/softeer/caecae/admin/service/AdminFindingGameService.java
  src/main/java/ai/softeer/caecae/findinggame/domain/entity/FindingGameWinner.java
  src/main/java/ai/softeer/caecae/findinggame/repository/FindingGameWinnerRepository.java
Labels: 진우
